apiVersion: apps/v1
 
kind: Deployment
 
metadata:
  name: app
 
spec:
 
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
 
    spec:
      containers:
        - name: app
          image: harryhare/testapp:test
          ports:
            - containerPort: 80
            
