apiVersion: v1

kind: Service

metadata:
  name: app-service
  labels:
    name: app-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
