Description: >
  udacity cloud ops project
  by mayue
  
Parameters:
  ProjectName:
    Description: project name
    Type: String
    Default: udacity cloud ops project 02
  VPCCidr:
    Description: ip range for scaling group
    Type: String
    Default: 10.0.0.0/16
  SubnetIpBlocks:
    Description: ip range for subnets
    Type: List<String>
    Default: "10.0.0.0/24, 10.0.1.0/24"
  Zones:
    Description: zones
    Type: List<String>
    Default: "us-west-2a, us-west-2b"
  Maxsize:
    Description: max size of vms in auto scaling group
    Type: String
    Default: 1 #4
  MinSize:
    Description: min size of vms in auto scaling group
    Type: String
    Default: 1 # 4
  ImageId:
    Description: image
    Type: String
    Default: "ami-0d1cd67c26f5fca19"
  InstanceType:
    Description: image
    Type: String
    Default: "t2.micro" # "t2.medium"
  UserData: 
    Description: script to run the website
    Type: String
    Default: 
      #!/bin/bash
      apt-get update -y
      apt-get install unzip awscli -y
      apt-get install apache2 -y
      systemctl start apache2.service
      cd /var/www/html
      aws s3 cp s3://udacity-demo-1/udacity.zip .
      unzip -o udacity.zip
      
Resources:

#########################################
#  vpc
#########################################

  VPCTest001:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref VPCCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
  PrivateNetwork001:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPCTest001
      CidrBlock:
        !Select [0, !Ref SubnetIpBlocks]
      AvailabilityZone:
        !Select [0, !Ref Zones]
  PrivateNetwork002:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPCTest001
      CidrBlock: 
        !Select [1, !Ref SubnetIpBlocks]
      AvailabilityZone:
        !Select [1, !Ref Zones]
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: test
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPCTest001
      InternetGatewayId: !Ref InternetGateway
      
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCTest001

  PublicInternetRouteTableEntry:
    Type: AWS::EC2::Route
    Properties:
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: '0.0.0.0/0'

  RouteTableAssociationAPublic:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateNetwork001
      RouteTableId: !Ref PublicRouteTable

  RouteTableAssociationBPublic:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateNetwork002
      RouteTableId: !Ref PublicRouteTable
      
#########################################
#  security group
#########################################

  WebSG:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: open 80 & 22
      GroupName: WebSG
      SecurityGroupEgress: 
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 53
          ToPort: 53
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId:
        Ref: VPCTest001
        
#########################################
# instances
#########################################

  WebLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties: 
      AssociatePublicIpAddress: true
      BlockDeviceMappings: 
        - DeviceName: /dev/sda1
          Ebs: 
            VolumeSize: 10
            DeleteOnTermination: true
      IamInstanceProfile: 
        !Ref ProfileWithRolesForOurApp
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      #KeyName: "udacity_project_cloudformation"
      PlacementTenancy: "default"
      SecurityGroups: 
        - !Ref WebSG
      UserData:
        Fn::Base64:
          !Sub |
              !Ref UserData
  Web:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties: 
      LaunchConfigurationName:
        !Ref WebLaunchConfiguration
      MaxSize: !Ref Maxsize
      MinSize: !Ref MinSize
      VPCZoneIdentifier: 
        - !Ref PrivateNetwork001
        - !Ref PrivateNetwork002
      TargetGroupARNs:
        - !Ref WebAppTargetGroup
    DependsOn: WebLaunchConfiguration
  
  ProfileWithRolesForOurApp:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles:
        - UdacityS3ReadOnlyEC2

#########################################
# load balancer
#########################################

  ELBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPCTest001
      GroupDescription: Enable HTTP/HTTPS access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebAppALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Scheme: internet-facing
      SecurityGroups:
        - !Ref ELBSecurityGroup
      Subnets:
        - !Ref PrivateNetwork001
        - !Ref PrivateNetwork002
      Type: application
  
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: 
            !Ref WebAppTargetGroup
      LoadBalancerArn:
        Ref: WebAppALB
      Port: 80
      Protocol: HTTP

  WebAppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VPCTest001
      HealthCheckIntervalSeconds: 60
      HealthCheckPath: /
      HealthCheckPort: 80
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      
      
 
 
#########################################
# outputs
#########################################
 
Outputs: 

  Region:
    Description: "region"
    Value:
      Ref: "AWS::Region"
    Export:
      Name: region
      
  AvailabilityZones:
    Description: AvailabilityZones
    Value:
      !Join 
        - ","
        - Fn::GetAZs: 
            Ref: "AWS::Region"
    Export:
      Name: AvailabilityZones
      
  AutoScalingGroupId:
    Description: AvailabilityZones
    Value:
      !Ref Web
    Export:
      Name: Web
      
  LBDNSName:
    Description: Web App ELB DNSName 
    Value:
      Fn::Join:
        - ""
        - - "http://"
          - Fn::GetAtt: WebAppALB.DNSName  
  